spring.application.name=bidwar


# ===============================
# DATABASE SETUP (Oracle)
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=C##HARSH
spring.datasource.password=harsh
spring.jpa.show-sql=true

# ===============================
# FILE UPLOAD LIMITS (For Images)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# SWAGGER SETUP
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# DDL AUTO (Careful!)
# ===============================
# Use 'update' usually. Use 'create' ONLY if you need to wipe/reset the DB.
spring.jpa.hibernate.ddl-auto=update